[INFO ] 2020-05-08 00:38:02.476 RepairAgencyApplicationListener:36 - Webapp 'Repair Service' was closed
[INFO ] 2020-05-08 00:38:38.339 RepairAgencyApplicationListener:26 - Webapp 'Repair Service' was started.
[ERROR] 2020-05-08 00:39:01.153 ExceptionHandleFilter:45 - Failed request (/RepairAgency/manager_home). Internal server error: 500 Can't get orders from database because of: Parameter index out of range (4 > number of parameters, which is 3).
ua.javaexternal_shulzhenko.repair_service.exceptions.DataBaseInteractionException: Can't get orders from database because of: Parameter index out of range (4 > number of parameters, which is 3).
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.OrdersDBService.getOrdersByOffsetAmountStatus(OrdersDBService.java:74) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.servlet.AppControllerServlet.doGet(AppControllerServlet.java:108) ~[classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.SessionCreateFilter.doFilter(SessionCreateFilter.java:22) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.ExceptionHandleFilter.doFilter(ExceptionHandleFilter.java:22) [classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: java.sql.SQLException: Parameter index out of range (4 > number of parameters, which is 3).
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.checkBounds(ClientPreparedStatement.java:1372) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.getCoreParameterIndex(ClientPreparedStatement.java:1385) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.setObject(ClientPreparedStatement.java:1669) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.setObject(DelegatingPreparedStatement.java:519) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.setObject(DelegatingPreparedStatement.java:519) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.dao.UniversalDAOFactory.insertSQLParams(UniversalDAOFactory.java:52) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.dao.UniversalDAOFactory.select(UniversalDAOFactory.java:18) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.OrdersDBService.getOrdersByOffsetAmountStatus(OrdersDBService.java:66) ~[classes/:?]
	... 33 more
[INFO ] 2020-05-08 00:44:24.811 RepairAgencyApplicationListener:36 - Webapp 'Repair Service' was closed
[INFO ] 2020-05-08 00:44:46.582 RepairAgencyApplicationListener:26 - Webapp 'Repair Service' was started.
[INFO ] 2020-05-08 00:53:03.037 RepairAgencyApplicationListener:36 - Webapp 'Repair Service' was closed
[INFO ] 2020-05-08 00:53:22.005 RepairAgencyApplicationListener:26 - Webapp 'Repair Service' was started.
[ERROR] 2020-05-08 00:58:02.881 ExceptionHandleFilter:45 - Failed request (/RepairAgency/order_history). Internal server error: 500 Can't get orders from database of such statuses because of: No value specified for parameter 4
ua.javaexternal_shulzhenko.repair_service.exceptions.DataBaseInteractionException: Can't get orders from database of such statuses because of: No value specified for parameter 4
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.OrdersDBService.getOrdersByAmountOffsetTwoStatuses(OrdersDBService.java:165) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.servlet.AppControllerServlet.doGet(AppControllerServlet.java:123) ~[classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.SessionCreateFilter.doFilter(SessionCreateFilter.java:22) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.ExceptionHandleFilter.doFilter(ExceptionHandleFilter.java:22) [classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: java.sql.SQLException: No value specified for parameter 4
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1020) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.dao.UniversalDAOFactory.select(UniversalDAOFactory.java:20) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.OrdersDBService.getOrdersByAmountOffsetTwoStatuses(OrdersDBService.java:160) ~[classes/:?]
	... 33 more
[ERROR] 2020-05-08 00:58:57.933 ExceptionHandleFilter:45 - Failed request (/RepairAgency/customers). Internal server error: 500 Can't get users amount from database because of: Table 'repair_agency.user' doesn't exist
ua.javaexternal_shulzhenko.repair_service.exceptions.DataBaseInteractionException: Can't get users amount from database because of: Table 'repair_agency.user' doesn't exist
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.UsersDBService.getUsersAmountByRole(UsersDBService.java:58) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.servlet.AppControllerServlet.doGet(AppControllerServlet.java:131) ~[classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.SessionCreateFilter.doFilter(SessionCreateFilter.java:22) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.ExceptionHandleFilter.doFilter(ExceptionHandleFilter.java:22) [classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: java.sql.SQLSyntaxErrorException: Table 'repair_agency.user' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.dao.UniversalDAOFactory.select(UniversalDAOFactory.java:20) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.UsersDBService.getUsersAmountByRole(UsersDBService.java:54) ~[classes/:?]
	... 33 more
[ERROR] 2020-05-08 00:59:01.847 ExceptionHandleFilter:45 - Failed request (/RepairAgency/masters). Internal server error: 500 Can't get users amount from database because of: Table 'repair_agency.user' doesn't exist
ua.javaexternal_shulzhenko.repair_service.exceptions.DataBaseInteractionException: Can't get users amount from database because of: Table 'repair_agency.user' doesn't exist
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.UsersDBService.getUsersAmountByRole(UsersDBService.java:58) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.servlet.AppControllerServlet.doGet(AppControllerServlet.java:135) ~[classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.SessionCreateFilter.doFilter(SessionCreateFilter.java:22) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.ExceptionHandleFilter.doFilter(ExceptionHandleFilter.java:22) [classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: java.sql.SQLSyntaxErrorException: Table 'repair_agency.user' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.dao.UniversalDAOFactory.select(UniversalDAOFactory.java:20) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.UsersDBService.getUsersAmountByRole(UsersDBService.java:54) ~[classes/:?]
	... 33 more
[INFO ] 2020-05-08 01:02:20.255 RepairAgencyApplicationListener:36 - Webapp 'Repair Service' was closed
[INFO ] 2020-05-08 01:03:10.112 RepairAgencyApplicationListener:26 - Webapp 'Repair Service' was started.
[ERROR] 2020-05-08 01:03:34.129 ExceptionHandleFilter:45 - Failed request (/RepairAgency/order_history). Internal server error: 500 Can't get orders from database of such statuses because of: No value specified for parameter 4
ua.javaexternal_shulzhenko.repair_service.exceptions.DataBaseInteractionException: Can't get orders from database of such statuses because of: No value specified for parameter 4
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.OrdersDBService.getOrdersByAmountOffsetTwoStatuses(OrdersDBService.java:167) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.servlet.AppControllerServlet.doGet(AppControllerServlet.java:123) ~[classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.SessionCreateFilter.doFilter(SessionCreateFilter.java:22) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.ExceptionHandleFilter.doFilter(ExceptionHandleFilter.java:22) [classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: java.sql.SQLException: No value specified for parameter 4
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1020) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.dao.UniversalDAOFactory.select(UniversalDAOFactory.java:20) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.OrdersDBService.getOrdersByAmountOffsetTwoStatuses(OrdersDBService.java:162) ~[classes/:?]
	... 33 more
[INFO ] 2020-05-08 01:06:59.941 RepairAgencyApplicationListener:36 - Webapp 'Repair Service' was closed
[INFO ] 2020-05-08 01:07:19.712 RepairAgencyApplicationListener:26 - Webapp 'Repair Service' was started.
[ERROR] 2020-05-08 01:08:24.183 ExceptionHandleFilter:45 - Failed request (/RepairAgency/order_history). Internal server error: 500 Can't get orders from database of such statuses because of: No value specified for parameter 4
ua.javaexternal_shulzhenko.repair_service.exceptions.DataBaseInteractionException: Can't get orders from database of such statuses because of: No value specified for parameter 4
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.OrdersDBService.getOrdersByAmountOffsetTwoStatuses(OrdersDBService.java:167) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.servlet.AppControllerServlet.doGet(AppControllerServlet.java:123) ~[classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.SessionCreateFilter.doFilter(SessionCreateFilter.java:22) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.ExceptionHandleFilter.doFilter(ExceptionHandleFilter.java:22) [classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: java.sql.SQLException: No value specified for parameter 4
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1020) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.dao.UniversalDAOFactory.select(UniversalDAOFactory.java:19) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.OrdersDBService.getOrdersByAmountOffsetTwoStatuses(OrdersDBService.java:162) ~[classes/:?]
	... 33 more
[ERROR] 2020-05-08 01:08:39.167 ExceptionHandleFilter:45 - Failed request (/RepairAgency/order_history). Internal server error: 500 Can't get orders from database of such statuses because of: No value specified for parameter 4
ua.javaexternal_shulzhenko.repair_service.exceptions.DataBaseInteractionException: Can't get orders from database of such statuses because of: No value specified for parameter 4
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.OrdersDBService.getOrdersByAmountOffsetTwoStatuses(OrdersDBService.java:167) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.servlet.AppControllerServlet.doGet(AppControllerServlet.java:123) ~[classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.SessionCreateFilter.doFilter(SessionCreateFilter.java:22) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.ExceptionHandleFilter.doFilter(ExceptionHandleFilter.java:22) [classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: java.sql.SQLException: No value specified for parameter 4
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1020) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.dao.UniversalDAOFactory.select(UniversalDAOFactory.java:19) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.OrdersDBService.getOrdersByAmountOffsetTwoStatuses(OrdersDBService.java:162) ~[classes/:?]
	... 33 more
[INFO ] 2020-05-08 01:15:16.634 RepairAgencyApplicationListener:36 - Webapp 'Repair Service' was closed
[INFO ] 2020-05-08 01:15:35.342 RepairAgencyApplicationListener:26 - Webapp 'Repair Service' was started.
[INFO ] 2020-05-08 01:24:24.014 RepairAgencyApplicationListener:36 - Webapp 'Repair Service' was closed
[INFO ] 2020-05-08 01:24:47.844 RepairAgencyApplicationListener:26 - Webapp 'Repair Service' was started.
[INFO ] 2020-05-08 01:30:18.867 RepairAgencyApplicationListener:36 - Webapp 'Repair Service' was closed
[INFO ] 2020-05-08 01:30:42.675 RepairAgencyApplicationListener:26 - Webapp 'Repair Service' was started.
[ERROR] 2020-05-08 01:32:20.166 ExceptionHandleFilter:45 - Failed request (/RepairAgency/customers). Internal server error: 500 Can't get users amount from database because of: Column 'amount' not found.
ua.javaexternal_shulzhenko.repair_service.exceptions.DataBaseInteractionException: Can't get users amount from database because of: Column 'amount' not found.
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.UsersDBService.getUsersAmountByRoleOffsetAmount(UsersDBService.java:59) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.servlet.AppControllerServlet.doGet(AppControllerServlet.java:132) ~[classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.SessionCreateFilter.doFilter(SessionCreateFilter.java:22) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.ExceptionHandleFilter.doFilter(ExceptionHandleFilter.java:22) [classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: java.sql.SQLException: Column 'amount' not found.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.result.ResultSetImpl.findColumn(ResultSetImpl.java:548) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:807) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at org.apache.commons.dbcp2.DelegatingResultSet.getInt(DelegatingResultSet.java:633) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at org.apache.commons.dbcp2.DelegatingResultSet.getInt(DelegatingResultSet.java:633) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.result_handler.ResultHandlerFactory.lambda$static$5(ResultHandlerFactory.java:96) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.dao.UniversalDAOFactory.select(UniversalDAOFactory.java:20) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.UsersDBService.getUsersAmountByRoleOffsetAmount(UsersDBService.java:54) ~[classes/:?]
	... 33 more
[ERROR] 2020-05-08 01:32:34.760 ExceptionHandleFilter:45 - Failed request (/RepairAgency/customers). Internal server error: 500 Can't get users amount from database because of: Column 'amount' not found.
ua.javaexternal_shulzhenko.repair_service.exceptions.DataBaseInteractionException: Can't get users amount from database because of: Column 'amount' not found.
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.UsersDBService.getUsersAmountByRoleOffsetAmount(UsersDBService.java:59) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.servlet.AppControllerServlet.doGet(AppControllerServlet.java:132) ~[classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.SessionCreateFilter.doFilter(SessionCreateFilter.java:22) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.ExceptionHandleFilter.doFilter(ExceptionHandleFilter.java:22) [classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: java.sql.SQLException: Column 'amount' not found.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.result.ResultSetImpl.findColumn(ResultSetImpl.java:548) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:807) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at org.apache.commons.dbcp2.DelegatingResultSet.getInt(DelegatingResultSet.java:633) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at org.apache.commons.dbcp2.DelegatingResultSet.getInt(DelegatingResultSet.java:633) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.result_handler.ResultHandlerFactory.lambda$static$5(ResultHandlerFactory.java:96) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.dao.UniversalDAOFactory.select(UniversalDAOFactory.java:20) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.UsersDBService.getUsersAmountByRoleOffsetAmount(UsersDBService.java:54) ~[classes/:?]
	... 33 more
[ERROR] 2020-05-08 01:32:35.800 ExceptionHandleFilter:45 - Failed request (/RepairAgency/masters). Internal server error: 500 Can't get users amount from database because of: Column 'amount' not found.
ua.javaexternal_shulzhenko.repair_service.exceptions.DataBaseInteractionException: Can't get users amount from database because of: Column 'amount' not found.
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.UsersDBService.getUsersAmountByRoleOffsetAmount(UsersDBService.java:59) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.servlet.AppControllerServlet.doGet(AppControllerServlet.java:137) ~[classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.SessionCreateFilter.doFilter(SessionCreateFilter.java:22) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.ExceptionHandleFilter.doFilter(ExceptionHandleFilter.java:22) [classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: java.sql.SQLException: Column 'amount' not found.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.result.ResultSetImpl.findColumn(ResultSetImpl.java:548) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:807) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at org.apache.commons.dbcp2.DelegatingResultSet.getInt(DelegatingResultSet.java:633) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at org.apache.commons.dbcp2.DelegatingResultSet.getInt(DelegatingResultSet.java:633) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.result_handler.ResultHandlerFactory.lambda$static$5(ResultHandlerFactory.java:96) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.dao.UniversalDAOFactory.select(UniversalDAOFactory.java:20) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.services.database_services.UsersDBService.getUsersAmountByRoleOffsetAmount(UsersDBService.java:54) ~[classes/:?]
	... 33 more
[INFO ] 2020-05-08 01:39:11.675 RepairAgencyApplicationListener:36 - Webapp 'Repair Service' was closed
[INFO ] 2020-05-08 01:39:35.164 RepairAgencyApplicationListener:26 - Webapp 'Repair Service' was started.
[INFO ] 2020-05-08 01:48:03.116 RepairAgencyApplicationListener:36 - Webapp 'Repair Service' was closed
[INFO ] 2020-05-08 01:48:24.508 RepairAgencyApplicationListener:26 - Webapp 'Repair Service' was started.
[INFO ] 2020-05-08 01:52:23.836 RepairAgencyApplicationListener:36 - Webapp 'Repair Service' was closed
[INFO ] 2020-05-08 01:52:42.003 RepairAgencyApplicationListener:26 - Webapp 'Repair Service' was started.
[INFO ] 2020-05-08 02:04:20.615 RepairAgencyApplicationListener:36 - Webapp 'Repair Service' was closed
[INFO ] 2020-05-08 02:04:42.847 RepairAgencyApplicationListener:26 - Webapp 'Repair Service' was started.
[ERROR] 2020-05-08 02:06:30.968 ExceptionHandleFilter:45 - Failed request (/RepairAgency/admin_home). Internal server error: 500 javax.servlet.ServletException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: org.apache.jasper.JasperException: /WEB-INF/jsp_pages/main_blocks/admin_page.jsp (line: [15], column: [16]) According to the TLD or the tag file, attribute [loop_num] is mandatory for tag [user_info]
org.apache.jasper.JasperException: javax.servlet.ServletException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: org.apache.jasper.JasperException: /WEB-INF/jsp_pages/main_blocks/admin_page.jsp (line: [15], column: [16]) According to the TLD or the tag file, attribute [loop_num] is mandatory for tag [user_info]
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:639) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:500) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) ~[jasper.jar:9.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.servlet.AppControllerServlet.doGet(AppControllerServlet.java:166) ~[classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.AuthorizationHandleFilter.doFilter(AuthorizationHandleFilter.java:21) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.SessionCreateFilter.doFilter(SessionCreateFilter.java:22) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.ExceptionHandleFilter.doFilter(ExceptionHandleFilter.java:22) [classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: javax.servlet.ServletException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: org.apache.jasper.JasperException: /WEB-INF/jsp_pages/main_blocks/admin_page.jsp (line: [15], column: [16]) According to the TLD or the tag file, attribute [loop_num] is mandatory for tag [user_info]
	at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:663) ~[jasper.jar:9.0.33]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspService(core_005fpage_jsp.java:205) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71) ~[jasper.jar:9.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477) ~[jasper.jar:9.0.33]
	... 49 more
Caused by: javax.servlet.jsp.JspException: org.apache.jasper.JasperException: /WEB-INF/jsp_pages/main_blocks/admin_page.jsp (line: [15], column: [16]) According to the TLD or the tag file, attribute [loop_num] is mandatory for tag [user_info]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke(core_005fpage_jsp.java:413) ~[?:?]
	at ua.javaexternal_shulzhenko.repair_service.tags.blocks.AbstractBlocksChildTag.doTag(AbstractBlocksChildTag.java:16) ~[classes/:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspx_meth_cust_005faside_002dmain_005f0(core_005fpage_jsp.java:315) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp.access$1(core_005fpage_jsp.java:302) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke0(core_005fpage_jsp.java:344) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke(core_005fpage_jsp.java:399) ~[?:?]
	at ua.javaexternal_shulzhenko.repair_service.tags.blocks.BlocksParentTag.doTag(BlocksParentTag.java:13) ~[classes/:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspx_meth_cust_005fblocks_005f0(core_005fpage_jsp.java:275) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspService(core_005fpage_jsp.java:175) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71) ~[jasper.jar:9.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477) ~[jasper.jar:9.0.33]
	... 49 more
Caused by: org.apache.jasper.JasperException: /WEB-INF/jsp_pages/main_blocks/admin_page.jsp (line: [15], column: [16]) According to the TLD or the tag file, attribute [loop_num] is mandatory for tag [user_info]
	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:42) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:292) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:115) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Validator$ValidateVisitor.visit(Validator.java:871) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1544) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2441) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Validator$ValidateVisitor.visit(Validator.java:907) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1544) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2441) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Validator$ValidateVisitor.visit(Validator.java:907) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1544) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2441) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Validator$ValidateVisitor.visit(Validator.java:907) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1544) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2441) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Validator$ValidateVisitor.visit(Validator.java:907) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1544) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2441) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Visitor.visit(Node.java:2447) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Root.accept(Node.java:470) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Validator.validateExDirectives(Validator.java:1857) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:224) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:386) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:362) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:346) ~[jasper.jar:9.0.33]
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:605) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:400) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) ~[jasper.jar:9.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:580) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:516) ~[catalina.jar:9.0.33]
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:955) ~[jasper.jar:9.0.33]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke2(core_005fpage_jsp.java:378) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke(core_005fpage_jsp.java:405) ~[?:?]
	at ua.javaexternal_shulzhenko.repair_service.tags.blocks.AbstractBlocksChildTag.doTag(AbstractBlocksChildTag.java:16) ~[classes/:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspx_meth_cust_005faside_002dmain_005f0(core_005fpage_jsp.java:315) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp.access$1(core_005fpage_jsp.java:302) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke0(core_005fpage_jsp.java:344) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke(core_005fpage_jsp.java:399) ~[?:?]
	at ua.javaexternal_shulzhenko.repair_service.tags.blocks.BlocksParentTag.doTag(BlocksParentTag.java:13) ~[classes/:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspx_meth_cust_005fblocks_005f0(core_005fpage_jsp.java:275) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspService(core_005fpage_jsp.java:175) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71) ~[jasper.jar:9.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477) ~[jasper.jar:9.0.33]
	... 49 more
[ERROR] 2020-05-08 02:06:36.961 ExceptionHandleFilter:45 - Failed request (/RepairAgency/man_mas_registration). Internal server error: 500 javax.servlet.ServletException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: org.apache.jasper.JasperException: /WEB-INF/jsp_pages/main_blocks/admin_page.jsp (line: [15], column: [16]) According to the TLD or the tag file, attribute [loop_num] is mandatory for tag [user_info]
org.apache.jasper.JasperException: javax.servlet.ServletException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: org.apache.jasper.JasperException: /WEB-INF/jsp_pages/main_blocks/admin_page.jsp (line: [15], column: [16]) According to the TLD or the tag file, attribute [loop_num] is mandatory for tag [user_info]
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:639) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:500) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) ~[jasper.jar:9.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.servlet.AppControllerServlet.doGet(AppControllerServlet.java:166) ~[classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.AuthorizationHandleFilter.doFilter(AuthorizationHandleFilter.java:21) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.SessionCreateFilter.doFilter(SessionCreateFilter.java:22) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.ExceptionHandleFilter.doFilter(ExceptionHandleFilter.java:22) [classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: javax.servlet.ServletException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: org.apache.jasper.JasperException: /WEB-INF/jsp_pages/main_blocks/admin_page.jsp (line: [15], column: [16]) According to the TLD or the tag file, attribute [loop_num] is mandatory for tag [user_info]
	at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:663) ~[jasper.jar:9.0.33]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspService(core_005fpage_jsp.java:205) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71) ~[jasper.jar:9.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477) ~[jasper.jar:9.0.33]
	... 49 more
Caused by: javax.servlet.jsp.JspException: org.apache.jasper.JasperException: /WEB-INF/jsp_pages/main_blocks/admin_page.jsp (line: [15], column: [16]) According to the TLD or the tag file, attribute [loop_num] is mandatory for tag [user_info]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke(core_005fpage_jsp.java:413) ~[?:?]
	at ua.javaexternal_shulzhenko.repair_service.tags.blocks.AbstractBlocksChildTag.doTag(AbstractBlocksChildTag.java:16) ~[classes/:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspx_meth_cust_005faside_002dmain_005f0(core_005fpage_jsp.java:315) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp.access$1(core_005fpage_jsp.java:302) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke0(core_005fpage_jsp.java:344) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke(core_005fpage_jsp.java:399) ~[?:?]
	at ua.javaexternal_shulzhenko.repair_service.tags.blocks.BlocksParentTag.doTag(BlocksParentTag.java:13) ~[classes/:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspx_meth_cust_005fblocks_005f0(core_005fpage_jsp.java:275) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspService(core_005fpage_jsp.java:175) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71) ~[jasper.jar:9.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477) ~[jasper.jar:9.0.33]
	... 49 more
Caused by: org.apache.jasper.JasperException: /WEB-INF/jsp_pages/main_blocks/admin_page.jsp (line: [15], column: [16]) According to the TLD or the tag file, attribute [loop_num] is mandatory for tag [user_info]
	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:42) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:292) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:115) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Validator$ValidateVisitor.visit(Validator.java:871) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1544) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2441) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Validator$ValidateVisitor.visit(Validator.java:907) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1544) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2441) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Validator$ValidateVisitor.visit(Validator.java:907) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1544) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2441) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Validator$ValidateVisitor.visit(Validator.java:907) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1544) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2441) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Validator$ValidateVisitor.visit(Validator.java:907) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1544) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2441) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Visitor.visit(Node.java:2447) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Root.accept(Node.java:470) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Validator.validateExDirectives(Validator.java:1857) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:224) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:386) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:362) ~[jasper.jar:9.0.33]
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:346) ~[jasper.jar:9.0.33]
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:605) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:400) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) ~[jasper.jar:9.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:580) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:516) ~[catalina.jar:9.0.33]
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:955) ~[jasper.jar:9.0.33]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke2(core_005fpage_jsp.java:378) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke(core_005fpage_jsp.java:405) ~[?:?]
	at ua.javaexternal_shulzhenko.repair_service.tags.blocks.AbstractBlocksChildTag.doTag(AbstractBlocksChildTag.java:16) ~[classes/:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspx_meth_cust_005faside_002dmain_005f0(core_005fpage_jsp.java:315) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp.access$1(core_005fpage_jsp.java:302) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke0(core_005fpage_jsp.java:344) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke(core_005fpage_jsp.java:399) ~[?:?]
	at ua.javaexternal_shulzhenko.repair_service.tags.blocks.BlocksParentTag.doTag(BlocksParentTag.java:13) ~[classes/:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspx_meth_cust_005fblocks_005f0(core_005fpage_jsp.java:275) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspService(core_005fpage_jsp.java:175) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71) ~[jasper.jar:9.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477) ~[jasper.jar:9.0.33]
	... 49 more
[ERROR] 2020-05-08 02:06:39.549 ExceptionHandleFilter:45 - Failed request (/RepairAgency/admin_home). Internal server error: 500 javax.servlet.ServletException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: org.apache.jasper.JasperException: An exception occurred processing [WEB-INF/jsp_pages/core_page.jsp] at line [42]

null

Stacktrace:
org.apache.jasper.JasperException: javax.servlet.ServletException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: org.apache.jasper.JasperException: An exception occurred processing [WEB-INF/jsp_pages/core_page.jsp] at line [42]

null

Stacktrace:
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:639) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:500) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) ~[jasper.jar:9.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.servlet.AppControllerServlet.doGet(AppControllerServlet.java:166) ~[classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.AuthorizationHandleFilter.doFilter(AuthorizationHandleFilter.java:21) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.SessionCreateFilter.doFilter(SessionCreateFilter.java:22) ~[classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at ua.javaexternal_shulzhenko.repair_service.filters.ExceptionHandleFilter.doFilter(ExceptionHandleFilter.java:22) [classes/:?]
	at ua.javaexternal_shulzhenko.repair_service.filters.AbstractFilter.doFilter(AbstractFilter.java:21) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688) [catalina.jar:9.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: javax.servlet.ServletException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: org.apache.jasper.JasperException: An exception occurred processing [WEB-INF/jsp_pages/core_page.jsp] at line [42]

null

Stacktrace:
	at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:663) ~[jasper.jar:9.0.33]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspService(core_005fpage_jsp.java:205) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71) ~[jasper.jar:9.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477) ~[jasper.jar:9.0.33]
	... 49 more
Caused by: javax.servlet.jsp.JspException: org.apache.jasper.JasperException: An exception occurred processing [WEB-INF/jsp_pages/core_page.jsp] at line [42]

null

Stacktrace:
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke(core_005fpage_jsp.java:413) ~[?:?]
	at ua.javaexternal_shulzhenko.repair_service.tags.blocks.AbstractBlocksChildTag.doTag(AbstractBlocksChildTag.java:16) ~[classes/:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspx_meth_cust_005faside_002dmain_005f0(core_005fpage_jsp.java:315) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp.access$1(core_005fpage_jsp.java:302) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke0(core_005fpage_jsp.java:344) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke(core_005fpage_jsp.java:399) ~[?:?]
	at ua.javaexternal_shulzhenko.repair_service.tags.blocks.BlocksParentTag.doTag(BlocksParentTag.java:13) ~[classes/:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspx_meth_cust_005fblocks_005f0(core_005fpage_jsp.java:275) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspService(core_005fpage_jsp.java:175) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71) ~[jasper.jar:9.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477) ~[jasper.jar:9.0.33]
	... 49 more
Caused by: org.apache.jasper.JasperException: An exception occurred processing [WEB-INF/jsp_pages/core_page.jsp] at line [42]

null

Stacktrace:
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:626) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:423) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) ~[jasper.jar:9.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:580) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:516) ~[catalina.jar:9.0.33]
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:955) ~[jasper.jar:9.0.33]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke2(core_005fpage_jsp.java:378) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke(core_005fpage_jsp.java:405) ~[?:?]
	at ua.javaexternal_shulzhenko.repair_service.tags.blocks.AbstractBlocksChildTag.doTag(AbstractBlocksChildTag.java:16) ~[classes/:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspx_meth_cust_005faside_002dmain_005f0(core_005fpage_jsp.java:315) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp.access$1(core_005fpage_jsp.java:302) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke0(core_005fpage_jsp.java:344) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke(core_005fpage_jsp.java:399) ~[?:?]
	at ua.javaexternal_shulzhenko.repair_service.tags.blocks.BlocksParentTag.doTag(BlocksParentTag.java:13) ~[classes/:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspx_meth_cust_005fblocks_005f0(core_005fpage_jsp.java:275) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspService(core_005fpage_jsp.java:175) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71) ~[jasper.jar:9.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477) ~[jasper.jar:9.0.33]
	... 49 more
Caused by: org.apache.jasper.JasperException: java.lang.ClassNotFoundException: org.apache.jsp.WEB_002dINF.jsp_005fpages.main_005fblocks.admin_005fpage_jsp
	at org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:198) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:414) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) ~[jasper.jar:9.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:580) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:516) ~[catalina.jar:9.0.33]
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:955) ~[jasper.jar:9.0.33]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke2(core_005fpage_jsp.java:378) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke(core_005fpage_jsp.java:405) ~[?:?]
	at ua.javaexternal_shulzhenko.repair_service.tags.blocks.AbstractBlocksChildTag.doTag(AbstractBlocksChildTag.java:16) ~[classes/:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspx_meth_cust_005faside_002dmain_005f0(core_005fpage_jsp.java:315) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp.access$1(core_005fpage_jsp.java:302) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke0(core_005fpage_jsp.java:344) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke(core_005fpage_jsp.java:399) ~[?:?]
	at ua.javaexternal_shulzhenko.repair_service.tags.blocks.BlocksParentTag.doTag(BlocksParentTag.java:13) ~[classes/:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspx_meth_cust_005fblocks_005f0(core_005fpage_jsp.java:275) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspService(core_005fpage_jsp.java:175) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71) ~[jasper.jar:9.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477) ~[jasper.jar:9.0.33]
	... 49 more
Caused by: java.lang.ClassNotFoundException: org.apache.jsp.WEB_002dINF.jsp_005fpages.main_005fblocks.admin_005fpage_jsp
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_231]
	at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:128) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:59) ~[jasper.jar:9.0.33]
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:159) ~[catalina.jar:9.0.33]
	at org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:193) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:414) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385) ~[jasper.jar:9.0.33]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) ~[jasper.jar:9.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:580) ~[catalina.jar:9.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:516) ~[catalina.jar:9.0.33]
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:955) ~[jasper.jar:9.0.33]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke2(core_005fpage_jsp.java:378) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke(core_005fpage_jsp.java:405) ~[?:?]
	at ua.javaexternal_shulzhenko.repair_service.tags.blocks.AbstractBlocksChildTag.doTag(AbstractBlocksChildTag.java:16) ~[classes/:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspx_meth_cust_005faside_002dmain_005f0(core_005fpage_jsp.java:315) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp.access$1(core_005fpage_jsp.java:302) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke0(core_005fpage_jsp.java:344) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp$Helper.invoke(core_005fpage_jsp.java:399) ~[?:?]
	at ua.javaexternal_shulzhenko.repair_service.tags.blocks.BlocksParentTag.doTag(BlocksParentTag.java:13) ~[classes/:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspx_meth_cust_005fblocks_005f0(core_005fpage_jsp.java:275) ~[?:?]
	at org.apache.jsp.WEB_002dINF.jsp_005fpages.core_005fpage_jsp._jspService(core_005fpage_jsp.java:175) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71) ~[jasper.jar:9.0.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477) ~[jasper.jar:9.0.33]
	... 49 more
[INFO ] 2020-05-08 02:09:15.308 RepairAgencyApplicationListener:36 - Webapp 'Repair Service' was closed
